### ISSUE TITLE
¿Para que es esta selección?

### ISSUE THREAD

**Issue by nekrum** [Albanene/Proyecto-DiEx#5]
Veo que estan seleccionado ciertas entradas en específico, cual es el criterio por el que lo hace @Albanene @carolina0909 @EderRazielSanchez 
Esto para replicarlo en la nueva sitnaxis que estamos replicando

https://github.com/Albanene/Proyecto-DiEx/blob/25d84e6e07047360cf45c8b36bd22caec8f338bd/proyecto.rmd#L45-L48

**Comment by Albanene** [comment]
De aquí queríamos obtener el número de ataques base para cada persona del grupo, eliminamos las demás columnas y sólo dejamos los de la columna V4 porque era la más fácil de seleccionar ya que en los otros periodos de dos semanas se repiten los ataques base
